language: java
  
sudo: true

jdk:
  - openjdk8
  - oraclejdk8

before_install:
  - wget https://github.com/MiniZinc/libminizinc/releases/download/2.1.6/minizinc-2.1.6-linux64.tar.gz
  - tar -xzf minizinc-2.1.6-linux64.tar.gz
  - export PATH=$PWD/minizinc-2.1.6/bin:$PATH
  - cd at.siemens.ct.jminizinc