language: java
  
sudo: true

jdk:
  - openjdk8
  - oraclejdk8

before_install:
  - wget https://github.com/MiniZinc/MiniZincIDE/releases/download/2.1.7/MiniZincIDE-2.1.7-bundle-linux-x86_64.tgz
  - tar -xzf MiniZincIDE-2.1.7-bundle-linux-x86_64.tgz
  - export PATH=$PWD/MiniZincIDE-2.1.7-bundle-linux-x86_64:$PATH
  - cd at.siemens.ct.jminizinc